baseurl = "https://jangari-ntk.github.io/"  # Include trailing slash
publishDir = "docs"
title = "vSoliloquy"
author = "Jangari"
copyright = "Copyright © 2025 VSOLILOQUY. All Rights Reserved."
theme = "hugo-clarity"

numberOfFeaturedPosts = 5

[pagination]
  pagerSize = 8

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false
    noClasses = false
    # style = "monokai"
    tabWidth = 2

[params]
author = "Jangari"
twitter = "@Jangari_nTK"
introDescription = "Jangari is a Technical Support Engineer working on a certain company in Japan."

# Google analytics Id
ga_analytics = "G-RVVR8FXTZ1"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png" 

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 0

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = true 


# directory(s) where your articles are located
mainSections = ["post"] # see config details here https://gohugo.io/functions/where/#mainsections

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

logo = "logos/logo.png"

# Label Non inline images on an article body
figurePositionShow = true # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'
